
CREATE TABLE IF NOT EXISTS learning_resources (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    topic_name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    difficulty_level VARCHAR(50),
    resource_type VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    url VARCHAR(2000) NOT NULL UNIQUE,
    description LONGTEXT,
    language VARCHAR(20) DEFAULT 'en',
    rating DECIMAL(3,2),
    rating_count INT DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_topic_name (topic_name),
    INDEX idx_resource_type (resource_type),
    INDEX idx_difficulty (difficulty_level),
    FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS user_recommended_resources (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    recommended_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    viewed_at TIMESTAMP NULL,
    INDEX idx_user_resources (user_id),
    INDEX idx_created_at (created_at),
    UNIQUE KEY unique_user_resource (user_id, resource_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (resource_id) REFERENCES learning_resources(id)
);
CREATE TABLE IF NOT EXISTS resource_feedback (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    resource_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT,
    comment LONGTEXT,
    is_helpful BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_resource_feedback (resource_id),
    INDEX idx_user_feedback (user_id),
    FOREIGN KEY (resource_id) REFERENCES learning_resources(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
INSERT IGNORE INTO learning_resources
(topic_name, category, difficulty_level, resource_type, title, url, description, language, rating, rating_count, is_verified, created_at)
VALUES
('String Pool', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java String Documentation',
 'https://docs.oracle.com/javase/tutorial/i18n/resbundle/propfile.html',
 'Official Java documentation for String class',
 'en', 5.0, 15, TRUE, CURRENT_TIMESTAMP),
('String Pool', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Understanding Java String Pool',
 'https://www.baeldung.com/java-string-pool',
 'Comprehensive article about String Pool mechanism in Java',
 'en', 4.8, 12, TRUE, CURRENT_TIMESTAMP),
('String Pool', 'Java Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Java String Pool Tutorial',
 'https://www.youtube.com/watch?v=2CSR5vBYvjg',
 'Video explanation of how String Pool works',
 'en', 4.5, 8, TRUE, CURRENT_TIMESTAMP),
('String Pool', 'Java Fundamentals', 'ADVANCED', 'PDF_BOOK',
 'Effective Java - Strings and Immutability',
 'https://www.amazon.com/Effective-Java-Joshua-Bloch/dp/0134685997',
 'Chapter on String management from Effective Java',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Memory Management', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Memory Management Guide',
 'https://docs.oracle.com/javase/tutorial/reflect/index.html',
 'Official guide on Java memory management',
 'en', 4.8, 10, TRUE, CURRENT_TIMESTAMP),
('Memory Management', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java Garbage Collection Explained',
 'https://www.baeldung.com/java-garbage-collection',
 'Deep dive into Java GC mechanisms',
 'en', 4.7, 14, TRUE, CURRENT_TIMESTAMP),
('Memory Management', 'Java Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Garbage Collection in Java',
 'https://www.youtube.com/watch?v=UnaNQgzZMIU',
 'Visual explanation of garbage collection',
 'en', 4.6, 9, TRUE, CURRENT_TIMESTAMP),
('Collections Framework', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Collections Framework Documentation',
 'https://docs.oracle.com/javase/tutorial/collections/',
 'Official Java Collections Framework tutorial',
 'en', 5.0, 18, TRUE, CURRENT_TIMESTAMP),
('Collections Framework', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java Collections Interview Questions',
 'https://www.baeldung.com/java-collections-interview-questions',
 'Common interview questions about Collections',
 'en', 4.6, 11, TRUE, CURRENT_TIMESTAMP),
('Collections Framework', 'Java Fundamentals', 'ADVANCED', 'PDF_BOOK',
 'Java Collections API Design',
 'https://www.amazon.com/Java-Generics-Collections-Maurice-Naftalin/dp/0596527756',
 'Advanced guide to Java Collections and Generics',
 'en', 4.8, 7, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Tutorials: Object-Oriented Programming Concepts',
 'https://docs.oracle.com/javase/tutorial/java/concepts/',
 'Official Oracle introduction to OOP in Java',
 'en', 5.0, 28, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'OOPs Concepts in Java',
 'https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/',
 'Detailed explanation with examples of all four pillars',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java OOP Concepts',
 'https://www.baeldung.com/java-oop',
 'Practical guide with code for inheritance, polymorphism etc.',
 'en', 4.8, 16, TRUE, CURRENT_TIMESTAMP),
('Exception Handling', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Tutorials: Exceptions',
 'https://docs.oracle.com/javase/tutorial/essential/exceptions/',
 'Official guide to try-catch, throw, custom exceptions',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Exception Handling', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java Exceptions Tutorial',
 'https://www.baeldung.com/java-exceptions',
 'Checked vs Unchecked, best practices, try-with-resources',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('Exception Handling', 'Java Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Java Exception Handling Explained',
 'https://www.youtube.com/watch?v=Lu-LHi3y1KQ',
 'Clear video with interview examples',
 'en', 4.7, 14, TRUE, CURRENT_TIMESTAMP),
('Multithreading', 'Java Concurrency', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Tutorials: Concurrency',
 'https://docs.oracle.com/javase/tutorial/essential/concurrency/',
 'Official intro to threads, synchronization, locks',
 'en', 5.0, 22, TRUE, CURRENT_TIMESTAMP),
('Multithreading', 'Java Concurrency', 'INTERMEDIATE', 'ARTICLE',
 'Java Concurrency and Multithreading',
 'https://www.baeldung.com/java-concurrency',
 'synchronized, volatile, ExecutorService, common issues',
 'en', 4.9, 25, TRUE, CURRENT_TIMESTAMP),
('Multithreading', 'Java Concurrency', 'ADVANCED', 'PDF_BOOK',
 'Java Concurrency in Practice',
 'https://www.amazon.com/Java-Concurrency-Practice-Brian-Goetz/dp/0321349601',
 'Classic book вЂ” must-read for concurrency questions',
 'en', 5.0, 30, TRUE, CURRENT_TIMESTAMP),
('Virtual Threads', 'Java Modern', 'ADVANCED', 'ARTICLE',
 'Virtual Threads in Java 21',
 'https://www.baeldung.com/java-virtual-threads',
 'Explanation of Project Loom and virtual threads (2026 hot topic)',
 'en', 4.8, 15, TRUE, CURRENT_TIMESTAMP),
('Java 8 Features', 'Java Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Java SE 8: Lambda Expressions',
 'https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html',
 'Official tutorial on lambdas and functional interfaces',
 'en', 4.8, 19, TRUE, CURRENT_TIMESTAMP),
('Java 8 Features', 'Java Modern', 'INTERMEDIATE', 'ARTICLE',
 'Java 8 New Features Guide',
 'https://www.baeldung.com/java-8-new-features',
 'Streams, Optional, default methods, complete overview',
 'en', 4.9, 26, TRUE, CURRENT_TIMESTAMP),
('Java 8 Features', 'Java Modern', 'INTERMEDIATE', 'VIDEO',
 'Java 8 Streams Tutorial',
 'https://www.youtube.com/watch?v=xmAxM8gk21s',
 'Practical stream tricks for interviews',
 'en', 4.7, 13, TRUE, CURRENT_TIMESTAMP),
('Collections Framework', 'Java Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Java Collections Tutorial',
 'https://docs.oracle.com/javase/tutorial/collections/',
 'Official docs вЂ” List, Set, Map, Queue',
 'en', 5.0, 24, TRUE, CURRENT_TIMESTAMP),
('HashMap Internals', 'Java Fundamentals', 'ADVANCED', 'ARTICLE',
 'How HashMap Works Internally in Java',
 'https://www.geeksforgeeks.org/internal-working-of-hashmap-java/',
 'Detailed internals: hashing, buckets, resize, Java 8 changes',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('HashMap Internals', 'Java Fundamentals', 'ADVANCED', 'ARTICLE',
 'HashMap Implementation in Java',
 'https://www.baeldung.com/java-hashmap',
 'Tree nodes, load factor, performance analysis',
 'en', 4.8, 17, TRUE, CURRENT_TIMESTAMP),
('JVM Internals', 'Java Advanced', 'INTERMEDIATE', 'ARTICLE',
 'JVM Architecture and Internals',
 'https://www.baeldung.com/jvm-internals',
 'Class loader, runtime data areas, execution engine',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('Garbage Collection', 'Java Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Java Garbage Collection Explained',
 'https://www.baeldung.com/java-garbage-collection',
 'GC algorithms, young/old gen, G1, ZGC (2026 relevant)',
 'en', 4.7, 16, TRUE, CURRENT_TIMESTAMP),
('JVM Internals', 'Java Advanced', 'ADVANCED', 'VIDEO',
 'Understanding the JVM',
 'https://www.youtube.com/watch?v=UnaNQgzZMIU',
 'Visual deep dive into JVM memory and GC',
 'en', 4.6, 12, TRUE, CURRENT_TIMESTAMP),
('Serialization', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java Serialization Guide',
 'https://www.baeldung.com/java-serialization',
 'Serializable, transient, serialVersionUID, pitfalls',
 'en', 4.8, 15, TRUE, CURRENT_TIMESTAMP),
('Generics', 'Java Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Java Tutorials: Generics',
 'https://docs.oracle.com/javase/tutorial/java/generics/',
 'Wildcards, bounded types, type erasure',
 'en', 4.9, 17, TRUE, CURRENT_TIMESTAMP),
('Generics', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Java Generics Tutorial',
 'https://www.baeldung.com/java-generics',
 'PECS rule, common mistakes in interviews',
 'en', 4.8, 14, TRUE, CURRENT_TIMESTAMP),
('Spring Boot', 'Java Frameworks', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Spring Boot Reference Documentation',
 'https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/',
 'Official getting started and core concepts',
 'en', 5.0, 20, TRUE, CURRENT_TIMESTAMP),
('Spring Boot', 'Java Frameworks', 'INTERMEDIATE', 'ARTICLE',
 'Spring Boot Tutorial',
 'https://www.baeldung.com/spring-boot',
 'REST API, auto-configuration, starters',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('Spring Boot', 'Java Frameworks', 'INTERMEDIATE', 'VIDEO',
 'Spring Boot Full Course',
 'https://www.youtube.com/watch?v=vtPkZShrvXQ',
 'Comprehensive free course for interview prep',
 'en', 4.8, 25, TRUE, CURRENT_TIMESTAMP),
('Java Interview Preparation', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 '150+ Core Java Interview Questions',
 'https://www.interviewbit.com/java-interview-questions/',
 'Huge list with answers вЂ” OOP, collections, threads etc.',
 'en', 4.9, 28, TRUE, CURRENT_TIMESTAMP),
('Java Interview Preparation', 'Java Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Top 100 Java Interview Questions 2026',
 'https://www.almabetter.com/bytes/articles/java-interview-questions',
 'Updated 2026 edition with explanations',
 'en', 4.8, 15, TRUE, CURRENT_TIMESTAMP),
('Lists vs Tuples', 'Python Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Python Tutorial: Data Structures - Lists and Tuples',
 'https://docs.python.org/3/tutorial/datastructures.html',
 'Official Python 3 docs: lists, tuples, sequences, mutability, when to use each',
 'en', 5.0, 28, TRUE, CURRENT_TIMESTAMP),
('Lists vs Tuples', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Difference Between List and Tuple in Python',
 'https://www.geeksforgeeks.org/python/python-difference-between-list-and-tuple/',
 'Updated 2025 article: mutability, performance, memory, key differences + examples',
 'en', 4.9, 25, TRUE, CURRENT_TIMESTAMP),
('Lists vs Tuples', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Lists and Tuples in Python',
 'https://realpython.com/python-lists-tuples/',
 'Practical guide: creation, methods, performance benchmarks, interview tips',
 'en', 4.8, 21, TRUE, CURRENT_TIMESTAMP),
('Lists vs Tuples', 'Python Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Python Tutorial for Beginners 4: Lists, Tuples, and Sets',
 'https://www.youtube.com/watch?v=W8KRzm-HUcc',
 'Corey Schafer вЂ” excellent visual explanation of differences',
 'en', 4.9, 26, TRUE, CURRENT_TIMESTAMP),
('Decorators', 'Python Advanced', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Python Glossary: decorator',
 'https://docs.python.org/3/glossary.html#term-decorator',
 'Official definition: function returning function, @ syntax sugar, examples with classmethod/staticmethod',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('Decorators', 'Python Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Primer on Python Decorators',
 'https://realpython.com/primer-on-python-decorators/',
 'Best comprehensive tutorial: basics, @wraps, decorators with args, class decorators, real examples',
 'en', 5.0, 32, TRUE, CURRENT_TIMESTAMP),
('Decorators', 'Python Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Decorators in Python',
 'https://www.geeksforgeeks.org/decorators-in-python/',
 'Practical examples: timing, logging, memoization + interview questions',
 'en', 4.8, 22, TRUE, CURRENT_TIMESTAMP),
('Decorators', 'Python Advanced', 'ADVANCED', 'VIDEO',
 'Python Decorators Explained',
 'https://www.youtube.com/watch?v=FsAPt_9Bf3U',
 'Advanced: stateful decorators, decorators with parameters, common patterns',
 'en', 4.7, 17, TRUE, CURRENT_TIMESTAMP),
('Generators', 'Python Advanced', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Python Tutorial: Iterators and Generators',
 'https://docs.python.org/3/tutorial/classes.html#iterators',
 'Official: iterators, generators, yield keyword explanation',
 'en', 4.9, 18, TRUE, CURRENT_TIMESTAMP),
('Generators', 'Python Advanced', 'INTERMEDIATE', 'ARTICLE',
 'How to Use Generators and yield in Python',
 'https://realpython.com/introduction-to-python-generators/',
 'In-depth: lazy evaluation, generator expressions, yield from, use cases',
 'en', 5.0, 25, TRUE, CURRENT_TIMESTAMP),
('Generators', 'Python Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Generators in Python',
 'https://www.geeksforgeeks.org/generators-in-python/',
 'Infinite generators, expressions, interview-focused examples',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Generators', 'Python Advanced', 'INTERMEDIATE', 'VIDEO',
 'Python Generators Explained',
 'https://www.youtube.com/watch?v=bD05uGo_sVI',
 'Corey Schafer вЂ” clear practical demonstration',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('GIL', 'Python Advanced', 'ADVANCED', 'ARTICLE',
 'What Is the Python Global Interpreter Lock (GIL)?',
 'https://realpython.com/python-gil/',
 'Detailed: why GIL, CPython threading limits, multiprocessing workaround',
 'en', 4.9, 23, TRUE, CURRENT_TIMESTAMP),
('GIL', 'Python Advanced', 'ADVANCED', 'ARTICLE',
 'Python GIL Explained',
 'https://www.geeksforgeeks.org/python-gil-global-interpreter-lock/',
 'Examples: threading vs multiprocessing, interview answers',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('GIL', 'Python Advanced', 'ADVANCED', 'VIDEO',
 'Understanding the Python GIL (David Beazley)',
 'https://www.youtube.com/watch?v=Obt-vMVdM8s',
 'Classic deep-dive talk on GIL internals',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Python Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Python Tutorial: Classes',
 'https://docs.python.org/3/tutorial/classes.html',
 'Official: __init__, inheritance, super(), special methods',
 'en', 5.0, 27, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Object-Oriented Programming (OOP) in Python',
 'https://realpython.com/python3-object-oriented-programming/',
 'Full OOP course: classes, inheritance, polymorphism, encapsulation',
 'en', 4.9, 24, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Python OOPS Concepts',
 'https://www.geeksforgeeks.org/python-oops-concepts/',
 'Four pillars with Python code examples',
 'en', 4.8, 21, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'Python Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Python OOP Tutorial - Corey Schafer series',
 'https://www.youtube.com/watch?v=ZDa-Z5JzLYM',
 'Playlist: classes to advanced OOP вЂ” interview gold',
 'en', 4.9, 25, TRUE, CURRENT_TIMESTAMP),
('Comprehensions', 'Python Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'List Comprehensions (in Data Structures)',
 'https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions',
 'Official: list, dict, set comprehensions, nested examples',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Comprehensions', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'List Comprehension in Python',
 'https://realpython.com/list-comprehension-python/',
 'Complete: list/dict/set/generator comprehensions + readability tips',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('Comprehensions', 'Python Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Python List Comprehensions Explained',
 'https://www.youtube.com/watch?v=fz2PKpPdlRo',
 'Practical walkthrough with examples',
 'en', 4.8, 16, TRUE, CURRENT_TIMESTAMP),
('Exception Handling', 'Python Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'Python Tutorial: Errors and Exceptions',
 'https://docs.python.org/3/tutorial/errors.html',
 'try-except, raise, else/finally, custom exceptions',
 'en', 5.0, 21, TRUE, CURRENT_TIMESTAMP),
('Exception Handling', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Python Exceptions: An Introduction',
 'https://realpython.com/python-exceptions/',
 'Best practices, custom exceptions, context managers integration',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Context Managers', 'Python Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Context Managers and the вЂњwithвЂќ Statement in Python',
 'https://realpython.com/python-with-statement/',
 'Custom context managers, __enter__/__exit__, generator-based',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('Async Await', 'Python Modern', 'ADVANCED', 'OFFICIAL_DOCS',
 'asyncio вЂ” Asynchronous I/O',
 'https://docs.python.org/3/library/asyncio.html',
 'Official: coroutines, tasks, event loop, gather, run',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('Async Await', 'Python Modern', 'ADVANCED', 'ARTICLE',
 'Async IO in Python: A Complete Walkthrough',
 'https://realpython.com/async-io-python/',
 'Top tutorial: async/await syntax, practical patterns',
 'en', 5.0, 24, TRUE, CURRENT_TIMESTAMP),
('Python Interview Preparation', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 '120+ Top Python Interview Questions and Answers (2026)',
 'https://www.interviewbit.com/python-interview-questions/',
 'Comprehensive: OOP, decorators, generators, GIL, async, comprehensions',
 'en', 4.9, 33, TRUE, CURRENT_TIMESTAMP),
('Python Interview Preparation', 'Python Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Python Interview Questions',
 'https://www.geeksforgeeks.org/python-interview-questions/',
 'Frequently asked questions + detailed answers',
 'en', 4.8, 28, TRUE, CURRENT_TIMESTAMP),
('Pointers & References', 'C++ Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'cppreference.com: Pointers',
 'https://en.cppreference.com/w/cpp/language/pointer',
 'Official reference: pointer declaration, dereference, pointer arithmetic',
 'en', 5.0, 25, TRUE, CURRENT_TIMESTAMP),
('Pointers & References', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Pointers in C++',
 'https://www.geeksforgeeks.org/pointers-in-c-cpp/',
 'Detailed: raw pointers, null, dangling, void*, interview examples',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('Pointers & References', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'References in C++',
 'https://www.learncpp.com/cpp-tutorial/references/',
 'LearnCpp: lvalue references, differences from pointers',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Pointers & References', 'C++ Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'C++ Pointers - The Cherno',
 'https://www.youtube.com/watch?v=2ybLD6_2gKM',
 'The Cherno series вЂ” clear explanation with examples',
 'en', 4.9, 24, TRUE, CURRENT_TIMESTAMP),
('Smart Pointers', 'C++ Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'cppreference.com: std::unique_ptr',
 'https://en.cppreference.com/w/cpp/memory/unique_ptr',
 'Official: unique_ptr semantics, make_unique, ownership',
 'en', 5.0, 23, TRUE, CURRENT_TIMESTAMP),
('Smart Pointers', 'C++ Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'cppreference.com: std::shared_ptr',
 'https://en.cppreference.com/w/cpp/memory/shared_ptr',
 'Shared ownership, reference counting, weak_ptr',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('Smart Pointers', 'C++ Modern', 'INTERMEDIATE', 'ARTICLE',
 'Smart Pointers in C++',
 'https://www.geeksforgeeks.org/smart-pointers-cpp/',
 'unique_ptr, shared_ptr, weak_ptr вЂ” use cases & pitfalls',
 'en', 4.8, 19, TRUE, CURRENT_TIMESTAMP),
('Smart Pointers', 'C++ Modern', 'INTERMEDIATE', 'VIDEO',
 'Smart Pointers in C++ - The Cherno',
 'https://www.youtube.com/watch?v=YokY6HzLkXs',
 'Practical demo: why raw pointers are dangerous',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('STL Containers', 'C++ Standard Library', 'BEGINNER', 'OFFICIAL_DOCS',
 'cppreference.com: Containers library',
 'https://en.cppreference.com/w/cpp/container',
 'Overview: sequence, associative, unordered containers',
 'en', 5.0, 24, TRUE, CURRENT_TIMESTAMP),
('STL Containers', 'C++ Standard Library', 'INTERMEDIATE', 'ARTICLE',
 'STL Containers in C++',
 'https://www.geeksforgeeks.org/the-c-standard-template-library-stl/',
 'vector vs list vs deque, map vs unordered_map, common operations',
 'en', 4.9, 23, TRUE, CURRENT_TIMESTAMP),
('STL Containers', 'C++ Standard Library', 'INTERMEDIATE', 'VIDEO',
 'C++ STL Tutorial - freeCodeCamp',
 'https://www.youtube.com/watch?v=6OoSgY6NVVk',
 'Full STL overview with code examples',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Virtual Functions', 'C++ OOP', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'cppreference.com: virtual function specifier',
 'https://en.cppreference.com/w/cpp/language/virtual',
 'Virtual, override, final, pure virtual, vtable',
 'en', 4.9, 18, TRUE, CURRENT_TIMESTAMP),
('Virtual Functions', 'C++ OOP', 'INTERMEDIATE', 'ARTICLE',
 'Virtual Functions in C++',
 'https://www.geeksforgeeks.org/virtual-functions-and-runtime-polymorphism-in-cpp/',
 'Polymorphism, overriding, abstract classes',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Virtual Functions', 'C++ OOP', 'INTERMEDIATE', 'VIDEO',
 'Virtual Functions / Polymorphism - The Cherno',
 'https://www.youtube.com/watch?v=3F6oE0QvS4w',
 'Excellent explanation with vtable demo',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('Move Semantics', 'C++ Modern', 'ADVANCED', 'OFFICIAL_DOCS',
 'cppreference.com: Move semantics',
 'https://en.cppreference.com/w/cpp/language/move_semantics',
 'std::move, rvalue references (&&), move constructor/assignment',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('Move Semantics', 'C++ Modern', 'ADVANCED', 'ARTICLE',
 'Move Semantics in C++',
 'https://www.geeksforgeeks.org/move-semantics-in-cpp/',
 'Perfect forwarding, rule of five, performance gains',
 'en', 4.8, 17, TRUE, CURRENT_TIMESTAMP),
('Move Semantics', 'C++ Modern', 'ADVANCED', 'VIDEO',
 'Move Semantics - cppcon talk',
 'https://www.youtube.com/watch?v=vT_hJ0Q3zRA',
 'Deep dive into move semantics (CppCon)',
 'en', 4.9, 18, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'C++ Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'cppreference.com: Classes',
 'https://en.cppreference.com/w/cpp/language/classes',
 'Class vs struct, constructors, destructors, access specifiers',
 'en', 5.0, 22, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Object Oriented Programming in C++',
 'https://www.learncpp.com/cpp-tutorial/introduction-to-object-oriented-programming/',
 'LearnCpp: full OOP series',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('OOP Principles', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'OOPs Concepts in C++',
 'https://www.geeksforgeeks.org/object-oriented-programming-in-cpp/',
 'Inheritance types, polymorphism, encapsulation',
 'en', 4.8, 19, TRUE, CURRENT_TIMESTAMP),
('Memory Management', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Dynamic Memory in C++',
 'https://www.learncpp.com/cpp-tutorial/dynamic-memory-allocation-with-new-and-delete/',
 'new, delete, RAII principle',
 'en', 4.9, 18, TRUE, CURRENT_TIMESTAMP),
('Memory Management', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'new and delete Operators in C++',
 'https://www.geeksforgeeks.org/new-and-delete-operators-in-cpp-for-dynamic-memory/',
 'Placement new, array new, common leaks',
 'en', 4.8, 16, TRUE, CURRENT_TIMESTAMP),
('Templates', 'C++ Advanced', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'cppreference.com: Templates',
 'https://en.cppreference.com/w/cpp/language/templates',
 'Function & class templates, specialization',
 'en', 4.9, 17, TRUE, CURRENT_TIMESTAMP),
('Templates', 'C++ Advanced', 'INTERMEDIATE', 'ARTICLE',
 'Templates in C++',
 'https://www.geeksforgeeks.org/templates-cpp/',
 'Generic programming, template parameters',
 'en', 4.8, 15, TRUE, CURRENT_TIMESTAMP),
('C++ Interview Preparation', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Top 50+ C++ Interview Questions (2026)',
 'https://www.interviewbit.com/cpp-interview-questions/',
 'Freshers to advanced: OOP, pointers, STL, modern C++',
 'en', 4.9, 30, TRUE, CURRENT_TIMESTAMP),
('C++ Interview Preparation', 'C++ Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'C++ Interview Questions',
 'https://www.geeksforgeeks.org/cpp/cpp-interview-questions/',
 'Frequently asked + code snippets',
 'en', 4.8, 28, TRUE, CURRENT_TIMESTAMP),
('C++ Interview Preparation', 'C++ Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'C++ Interview Questions 2026',
 'https://www.youtube.com/watch?v=4qKbyPejodU',
 'Roadmap + common questions walkthrough',
 'en', 4.7, 20, TRUE, CURRENT_TIMESTAMP),
('Closures', 'JavaScript Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Closures',
 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures',
 'Official MDN: what closures are, lexical scoping, practical examples',
 'en', 5.0, 30, TRUE, CURRENT_TIMESTAMP),
('Closures', 'JavaScript Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'JavaScript Closures',
 'https://www.geeksforgeeks.org/closure-in-javascript/',
 'Detailed with code: module pattern, private variables, interview Q&A',
 'en', 4.9, 25, TRUE, CURRENT_TIMESTAMP),
('Closures', 'JavaScript Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'JavaScript Closures Explained',
 'https://www.youtube.com/watch?v=CQqwU2Ixu-U',
 'freeCodeCamp / Traversy вЂ” clear visual explanation',
 'en', 4.9, 28, TRUE, CURRENT_TIMESTAMP),
('Hoisting', 'JavaScript Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'MDN: Hoisting',
 'https://developer.mozilla.org/en-US/docs/Glossary/Hoisting',
 'Official: var/let/const hoisting, function declarations',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('Hoisting', 'JavaScript Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Hoisting in JavaScript',
 'https://www.interviewbit.com/javascript-interview-questions/#hoisting',
 'InterviewBit: common pitfalls, temporal dead zone',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Event Loop', 'JavaScript Advanced', 'ADVANCED', 'OFFICIAL_DOCS',
 'MDN: Concurrency model and the event loop',
 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop',
 'Official explanation: call stack, task queues, microtasks',
 'en', 5.0, 26, TRUE, CURRENT_TIMESTAMP),
('Event Loop', 'JavaScript Advanced', 'ADVANCED', 'ARTICLE',
 'The JavaScript Event Loop',
 'https://www.geeksforgeeks.org/javascript-event-loop/',
 'With diagrams, setTimeout vs Promise, interview examples',
 'en', 4.8, 19, TRUE, CURRENT_TIMESTAMP),
('Event Loop', 'JavaScript Advanced', 'ADVANCED', 'VIDEO',
 'Event Loop in JavaScript',
 'https://www.youtube.com/watch?v=8aGhZQkoFbQ',
 'Loupe tool demo вЂ” must-watch',
 'en', 4.9, 24, TRUE, CURRENT_TIMESTAMP),
('Promises Async', 'JavaScript Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Promise',
 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
 'Official: then/catch/finally, Promise.all/race',
 'en', 5.0, 25, TRUE, CURRENT_TIMESTAMP),
('Promises Async', 'JavaScript Modern', 'INTERMEDIATE', 'ARTICLE',
 'Async/Await in JavaScript',
 'https://www.geeksforgeeks.org/async-await-function-in-javascript/',
 'Error handling, top-level await, real examples',
 'en', 4.8, 21, TRUE, CURRENT_TIMESTAMP),
('Promises Async', 'JavaScript Modern', 'INTERMEDIATE', 'VIDEO',
 'JavaScript Promises and Async Await',
 'https://www.youtube.com/watch?v=li7FzD6TNxQ',
 'freeCodeCamp full tutorial',
 'en', 4.9, 27, TRUE, CURRENT_TIMESTAMP),
('Prototypes this', 'JavaScript Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Inheritance and the prototype chain',
 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain',
 'Prototype chain, Object.create, classes under the hood',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Prototypes this', 'JavaScript Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'this Keyword in JavaScript',
 'https://www.interviewbit.com/javascript-interview-questions/#this-keyword',
 'this binding: call/apply/bind, arrow functions',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('ES6 Features', 'JavaScript Modern', 'BEGINNER', 'OFFICIAL_DOCS',
 'MDN: Destructuring assignment',
 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment',
 'Array/object destructuring, defaults',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('ES6 Features', 'JavaScript Modern', 'INTERMEDIATE', 'ARTICLE',
 'ES6 Interview Questions',
 'https://www.geeksforgeeks.org/es6-interview-questions/',
 'Spread/rest, arrow funcs, template literals',
 'en', 4.8, 17, TRUE, CURRENT_TIMESTAMP),
('JavaScript Interview Preparation', 'JavaScript Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 '100+ JavaScript Interview Questions (2026)',
 'https://www.interviewbit.com/javascript-interview-questions/',
 'Curated list: freshers to advanced, closures to modules',
 'en', 4.9, 35, TRUE, CURRENT_TIMESTAMP),
('JavaScript Interview Preparation', 'JavaScript Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'JavaScript Interview Questions',
 'https://www.geeksforgeeks.org/javascript-interview-questions-and-answers/',
 'Updated 2026, coding + theory',
 'en', 4.8, 30, TRUE, CURRENT_TIMESTAMP),
('.NET Core Basics', 'C# Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'What is .NET?',
 'https://learn.microsoft.com/en-us/dotnet/fundamentals/overview',
 'Official: .NET vs .NET Framework vs .NET Core, cross-platform',
 'en', 5.0, 25, TRUE, CURRENT_TIMESTAMP),
('.NET Core Basics', 'C# Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 '.NET Core Interview Questions',
 'https://www.interviewbit.com/dot-net-interview-questions/',
 'Differences, runtime, libraries',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('Async Await', 'C# Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Asynchronous programming',
 'https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/',
 'Task, async/await, ConfigureAwait, pitfalls',
 'en', 5.0, 24, TRUE, CURRENT_TIMESTAMP),
('Async Await', 'C# Modern', 'INTERMEDIATE', 'ARTICLE',
 'Async Await in C#',
 'https://www.geeksforgeeks.org/async-and-await-in-c-sharp/',
 'Examples, deadlocks avoidance',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('LINQ', 'C# Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'LINQ (Language Integrated Query)',
 'https://learn.microsoft.com/en-us/dotnet/csharp/linq/',
 'Query syntax vs method, deferred execution',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('Dependency Injection', 'ASP.NET Core', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'Dependency injection in .NET',
 'https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection',
 'Services lifetime: transient/scoped/singleton',
 'en', 5.0, 23, TRUE, CURRENT_TIMESTAMP),
('Middleware', 'ASP.NET Core', 'ADVANCED', 'OFFICIAL_DOCS',
 'ASP.NET Core Middleware',
 'https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/',
 'Pipeline order, Use/Run/Map, custom middleware',
 'en', 4.9, 19, TRUE, CURRENT_TIMESTAMP),
('C# Interview Preparation', 'C# Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Top 70+ .NET Interview Questions (2026)',
 'https://www.interviewbit.com/dot-net-interview-questions/',
 'C#, .NET Core, ASP.NET, EF Core',
 'en', 4.9, 32, TRUE, CURRENT_TIMESTAMP),
('C# Interview Preparation', 'C# Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 '.NET Interview Questions',
 'https://www.geeksforgeeks.org/c-sharp-interview-questions/',
 'Updated with .NET 8/9 features',
 'en', 4.8, 28, TRUE, CURRENT_TIMESTAMP),
('Semantic HTML', 'HTML Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'MDN: HTML5 semantic elements',
 'https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html',
 'Official: <header>, <nav>, <main>, <article>, <section>, <aside>, <footer> вЂ” why use over <div>',
 'en', 5.0, 28, TRUE, CURRENT_TIMESTAMP),
('Semantic HTML', 'HTML Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Semantic HTML Interview Questions',
 'https://www.geeksforgeeks.org/html-semantic-elements/',
 'Benefits: accessibility, SEO, screen readers, code readability',
 'en', 4.9, 24, TRUE, CURRENT_TIMESTAMP),
('Semantic HTML', 'HTML Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'Semantic HTML5 Elements Explained',
 'https://www.youtube.com/watch?v=2hY1S6S0b0w',
 'Kevin Powell вЂ” practical examples for interviews',
 'en', 4.9, 26, TRUE, CURRENT_TIMESTAMP),
('Accessibility', 'HTML Advanced', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Accessibility in HTML',
 'https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML',
 'ARIA roles, alt text, semantic elements, focus management',
 'en', 5.0, 25, TRUE, CURRENT_TIMESTAMP),
('Accessibility', 'HTML Advanced', 'INTERMEDIATE', 'ARTICLE',
 'HTML Accessibility Interview Questions',
 'https://www.interviewbit.com/html-interview-questions/#accessibility',
 'Common Q: alt vs title, landmark roles, skip links',
 'en', 4.8, 22, TRUE, CURRENT_TIMESTAMP),
('Box Model', 'CSS Fundamentals', 'BEGINNER', 'OFFICIAL_DOCS',
 'MDN: CSS Box Model',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model',
 'content-box vs border-box, margin collapse, padding',
 'en', 5.0, 30, TRUE, CURRENT_TIMESTAMP),
('Box Model', 'CSS Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'CSS Box Model Explained',
 'https://www.geeksforgeeks.org/css-box-model/',
 'Interview traps: margin collapsing, negative margins',
 'en', 4.9, 23, TRUE, CURRENT_TIMESTAMP),
('Box Model', 'CSS Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'CSS Box Model Tutorial',
 'https://www.youtube.com/watch?v=4qX1v1j9c0k',
 'freeCodeCamp вЂ” visual demo with code',
 'en', 4.9, 27, TRUE, CURRENT_TIMESTAMP),
('Positioning', 'CSS Layout', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: position',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/position',
 'Differences: static/relative/absolute/fixed/sticky, z-index stacking',
 'en', 4.9, 21, TRUE, CURRENT_TIMESTAMP),
('Positioning', 'CSS Layout', 'INTERMEDIATE', 'ARTICLE',
 'CSS Positioning Interview Questions',
 'https://www.interviewbit.com/css-interview-questions/#positioning',
 'Common: sticky header, modal positioning pitfalls',
 'en', 4.8, 19, TRUE, CURRENT_TIMESTAMP),
('Flexbox Grid', 'CSS Layout', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: CSS Flexible Box Layout',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox',
 'Flexbox: one-dimensional, align-items, justify-content',
 'en', 5.0, 26, TRUE, CURRENT_TIMESTAMP),
('Flexbox Grid', 'CSS Layout', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: CSS Grid Layout',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout',
 'Grid: two-dimensional, grid-template-columns/rows, subgrid',
 'en', 5.0, 24, TRUE, CURRENT_TIMESTAMP),
('Flexbox Grid', 'CSS Layout', 'INTERMEDIATE', 'VIDEO',
 'Flexbox vs Grid - Which to Use?',
 'https://www.youtube.com/watch?v=JJSoEo8JSnc',
 'Kevin Powell вЂ” real comparison for interviews',
 'en', 4.9, 28, TRUE, CURRENT_TIMESTAMP),
('Responsive Design', 'CSS Modern', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Media Queries',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries',
 'min-width/max-width, mobile-first, viewport meta',
 'en', 4.9, 22, TRUE, CURRENT_TIMESTAMP),
('Responsive Design', 'CSS Modern', 'INTERMEDIATE', 'ARTICLE',
 'Responsive Web Design Interview Questions',
 'https://www.geeksforgeeks.org/responsive-web-design-media-queries/',
 'Fluid layouts, breakpoints, rem/em vs px',
 'en', 4.8, 20, TRUE, CURRENT_TIMESTAMP),
('Modern CSS', 'CSS Advanced', 'ADVANCED', 'OFFICIAL_DOCS',
 'MDN: :has() pseudo-class',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/:has',
 'Parent selector, conditional styling based on children',
 'en', 4.9, 18, TRUE, CURRENT_TIMESTAMP),
('Modern CSS', 'CSS Advanced', 'ADVANCED', 'OFFICIAL_DOCS',
 'MDN: Container queries',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries',
 '@container, size queries, style queries вЂ” component-based responsive',
 'en', 5.0, 19, TRUE, CURRENT_TIMESTAMP),
('Modern CSS', 'CSS Advanced', 'ADVANCED', 'ARTICLE',
 'clamp(), min(), max() in CSS',
 'https://www.interviewbit.com/css-interview-questions/#clamp',
 'Fluid typography/sizing: clamp( min, preferred, max )',
 'en', 4.8, 17, TRUE, CURRENT_TIMESTAMP),
('Specificity', 'CSS Fundamentals', 'INTERMEDIATE', 'OFFICIAL_DOCS',
 'MDN: Specificity',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity',
 'Calculation: inline > ID > class > element, !important',
 'en', 4.9, 20, TRUE, CURRENT_TIMESTAMP),
('Specificity', 'CSS Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'CSS Specificity Interview Questions',
 'https://www.geeksforgeeks.org/css-specificity/',
 'Common traps, cascade layers (@layer)',
 'en', 4.8, 18, TRUE, CURRENT_TIMESTAMP),
('HTML CSS Interview Preparation', 'Front-end Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'Top 80+ CSS Interview Questions (2026)',
 'https://www.interviewbit.com/css-interview-questions-2026',
 'Comprehensive: box model to container queries, :has(), BEM',
 'en', 4.9, 35, TRUE, CURRENT_TIMESTAMP),
('HTML CSS Interview Preparation', 'Front-end Fundamentals', 'INTERMEDIATE', 'ARTICLE',
 'HTML Interview Questions (2026)',
 'https://www.interviewbit.com/html-interview-questions',
 'Semantics, forms, accessibility, HTML5 APIs',
 'en', 4.9, 32, TRUE, CURRENT_TIMESTAMP),
('HTML CSS Interview Preparation', 'Front-end Fundamentals', 'INTERMEDIATE', 'VIDEO',
 'HTML & CSS Interview Questions 2026',
 'https://www.youtube.com/watch?v=SqFhmg1Tdz0',
 'Top questions walkthrough for frontend roles',
 'en', 4.8, 25, TRUE);